name: GitHub CI
on:
  push:
    branches:
      - ksp-deobfuscation
  pull_request:
    branches:
      - ksp-deobfuscation
  release:
    types: released

env:
  CI_REQ_DOTNET_SDK_VER: 5.0.100

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      - name: Build dnSpy (.NET x64)
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1 net-x64
          New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
          Compress-Archive -Path dnSpy\dnSpy\bin\Release\net5.0-windows\win-x64\publish\* -DestinationPath C:\builtfiles\dnSpy-net-win64.zip
          .\clean-all.cmd

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/ksp-deobfuscation' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-net-win64
          path: C:\builtfiles\dnSpy-net-win64.zip
          if-no-files-found: error
